/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwaretermodinamica.telas;

import java.text.DecimalFormat;
import softwaretermodinamica.bancodedados.DAO;
import softwaretermodinamica.bancodedados.PropriedadesDeEspeciesPuras;
import softwaretermodinamica.bancodedados.TabelaAntoine;
import softwaretermodinamica.pressaodesaturacao.Antoine;
import softwaretermodinamica.pressaodesaturacao.CorrelacaoLeeKesler;

/**
 *
 * @author Willian Belincanta Ribeiro
 */
public class PressaoDeSaturacao extends javax.swing.JFrame {

    /**
     * Creates new form PressaoDeSaturacao
     */
    public PressaoDeSaturacao() {
        initComponents();
        panelAntoine.setVisible(false);
        panelAntoine2.setVisible(false);
        panelLee.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saturacao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        antoine = new javax.swing.JRadioButton();
        lee = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        cbComposto = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        temperatura = new javax.swing.JTextField();
        cbUnidade = new javax.swing.JComboBox<>();
        panelEquacao = new javax.swing.JPanel();
        panelAntoine = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelAntoine2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelC = new javax.swing.JLabel();
        labelB = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelLee = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        calcularPressaoSat = new javax.swing.JButton();
        panelResultado = new javax.swing.JPanel();
        resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pressão de Saturação");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pressão de Saturação");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(572, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1002, -1));

        antoine.setBackground(new java.awt.Color(255, 255, 255));
        saturacao.add(antoine);
        antoine.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        antoine.setText("Equação de Antoine");
        antoine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antoineActionPerformed(evt);
            }
        });
        jPanel1.add(antoine, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        lee.setBackground(new java.awt.Color(255, 255, 255));
        saturacao.add(lee);
        lee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lee.setText("Correlação Lee-Kesler");
        lee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leeActionPerformed(evt);
            }
        });
        jPanel1.add(lee, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Selecione o composto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        cbComposto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbComposto, 0, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(cbComposto, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 470, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Temperatura de saturação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        temperatura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        temperatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cbUnidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ºC", "K", "R", "ºF" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(cbUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 470, 70));

        panelEquacao.setBackground(new java.awt.Color(255, 255, 255));
        panelEquacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Equação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panelEquacao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAntoine.setBackground(new java.awt.Color(255, 255, 255));
        panelAntoine.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>ln P<sup>sat</sup> [kPa] = ");
        panelAntoine.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("A");
        panelAntoine.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        panelAntoine.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 25, 12, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("T");
        panelAntoine.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("+");
        panelAntoine.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("C");
        panelAntoine.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jlabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel8.setText("B");
        panelAntoine.add(jlabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 13, 30, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softwaretermodinamica/telas/imagens/linha.png"))); // NOI18N
        panelAntoine.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 35, 50, -1));

        panelEquacao.add(panelAntoine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 60));

        panelAntoine2.setBackground(new java.awt.Color(255, 255, 255));
        panelAntoine2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html>ln P<sup>sat</sup> [kPa] =");
        panelAntoine2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        labelA.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelA.setText("A");
        panelAntoine2.add(labelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 27, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("-");
        panelAntoine2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 27, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("T");
        panelAntoine2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("+");
        panelAntoine2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        labelC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelC.setText("C");
        panelAntoine2.add(labelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        labelB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelB.setText("B");
        panelAntoine2.add(labelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 15, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softwaretermodinamica/telas/imagens/linha.png"))); // NOI18N
        panelAntoine2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 35, 100, -1));

        panelEquacao.add(panelAntoine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 60));

        panelLee.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("<html>ln Pr<sup>sat</sup>(Tr) = ln Pr<sup>(0)</sup>(Tr) + &omega * ln Pr<sup>(1)</sup>(Tr)");

        javax.swing.GroupLayout panelLeeLayout = new javax.swing.GroupLayout(panelLee);
        panelLee.setLayout(panelLeeLayout);
        panelLeeLayout.setHorizontalGroup(
            panelLeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(panelLeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLeeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelLeeLayout.setVerticalGroup(
            panelLeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(panelLeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLeeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelEquacao.add(panelLee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 60));

        jPanel1.add(panelEquacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 470, 90));

        calcularPressaoSat.setBackground(new java.awt.Color(255, 255, 255));
        calcularPressaoSat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        calcularPressaoSat.setText("CALCULAR");
        calcularPressaoSat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularPressaoSatActionPerformed(evt);
            }
        });
        jPanel1.add(calcularPressaoSat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 110, 30));

        panelResultado.setBackground(new java.awt.Color(255, 255, 255));
        panelResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html> P<sup>sat</sup> - Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        resultado.setBackground(new java.awt.Color(255, 255, 255));
        resultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanel1.add(panelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 470, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularPressaoSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularPressaoSatActionPerformed
        if (antoine.isSelected()) {

            switch (cbUnidade.getSelectedItem().toString()) {
                case "ºC":
                    float t = Float.parseFloat(temperatura.getText());
                    Antoine.setTemperatura(t);
                    break;

                case "K":
                    float T = (float) (Float.parseFloat(temperatura.getText()) - 273.15);
                    Antoine.setTemperatura(T);
                    break;

                case "R":
                    float Temp = (float) ((Float.parseFloat(temperatura.getText()) * 0.55555555555555555555555555555556) - 273.15);
                    Antoine.setTemperatura(Temp);
                    break;

                case "ºF":
                    float temp = (float) ((Float.parseFloat(temperatura.getText()) - 32) / 1.8);
                    Antoine.setTemperatura(temp);
                    break;
            }

            DecimalFormat df = new DecimalFormat("0.0000");
            String composto = cbComposto.getSelectedItem().toString();
            DAO.buscarAntoine(composto);
            Antoine.calcularPressao();
            labelA.setText(Float.toString(Antoine.getA()));
            labelB.setText(Float.toString(Antoine.getB()));
            labelC.setText(Float.toString(Antoine.getC()));
            panelAntoine.setVisible(false);
            panelAntoine2.setVisible(true);
            resultado.setVisible(true);
            resultado.setText(df.format(Antoine.getPressao()) + " kPa");

        } else if (lee.isSelected()) {

            switch (cbUnidade.getSelectedItem().toString()) {
                case "ºC":
                    float b = (float) (Float.parseFloat(temperatura.getText()) + 273.15);
                    CorrelacaoLeeKesler.setTemperatura(b);
                    break;

                case "K":
                    float c = Float.parseFloat(temperatura.getText());
                    CorrelacaoLeeKesler.setTemperatura(c);
                    break;

                case "R":
                    float d = (float) (Float.parseFloat(temperatura.getText()) / 1.8);
                    CorrelacaoLeeKesler.setTemperatura(d);
                    break;

                case "ºF":
                    float e = (float) ((Float.parseFloat(temperatura.getText()) + 459.67) / 1.8);
                    CorrelacaoLeeKesler.setTemperatura(e);
                    break;
            }

            DecimalFormat d = new DecimalFormat("0.0000");
            String composto = cbComposto.getSelectedItem().toString();
            DAO.buscar(composto);
            CorrelacaoLeeKesler.calcularPressao();
            resultado.setVisible(true);
            resultado.setText(d.format(CorrelacaoLeeKesler.getPressao()) + " Pa");

        }
    }//GEN-LAST:event_calcularPressaoSatActionPerformed

    private void antoineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antoineActionPerformed
        panelAntoine.setVisible(true);
        resultado.setVisible(false);
        cbComposto.removeAllItems();
        DAO d = new DAO();
        for (TabelaAntoine a : d.leituraAntoine()) {
            cbComposto.addItem(a);
        }
    }//GEN-LAST:event_antoineActionPerformed

    private void leeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leeActionPerformed
        cbComposto.removeAllItems();
        panelAntoine.setVisible(false);
        panelAntoine2.setVisible(false);
        resultado.setVisible(false);
        DAO d = new DAO();
        for (PropriedadesDeEspeciesPuras p : d.leituraPropriedades()) {
            cbComposto.addItem(p);
        }
        panelLee.setVisible(true);
    }//GEN-LAST:event_leeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PressaoDeSaturacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PressaoDeSaturacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PressaoDeSaturacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PressaoDeSaturacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PressaoDeSaturacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton antoine;
    private javax.swing.JButton calcularPressaoSat;
    private javax.swing.JComboBox<Object> cbComposto;
    private javax.swing.JComboBox<String> cbUnidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelB;
    private javax.swing.JLabel labelC;
    private javax.swing.JRadioButton lee;
    private javax.swing.JPanel panelAntoine;
    private javax.swing.JPanel panelAntoine2;
    private javax.swing.JPanel panelEquacao;
    private javax.swing.JPanel panelLee;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JLabel resultado;
    private javax.swing.ButtonGroup saturacao;
    private javax.swing.JTextField temperatura;
    // End of variables declaration//GEN-END:variables
}
